#!/usr/bin/env bash

#--------------
# Usage:
# 1, cd到一个文件夹，此文件夹拥有众多git仓库
# 2，目前不支持git仓库的目录嵌套
# 3，执行 pullp，将会自动对此文件夹的所有git仓库执行 git pull -p
#--------------

path=.

function listDir() {
    for el in `ls $1`; do
        dir_or_file=${1}/${el}

        if [[ -d $dir_or_file ]]; then
            # listDir $dir_or_file
            echo "cd in ${dir_or_file}, and exec git pull -p"
            cd $dir_or_file
            git pull -p
            cd ..
            echo
        else
            echo "${dir_or_file} is a file. skip it."
        fi
    done
}

listDir $path
